services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: ClickNcart
    ports:
      - "3306:3306"
    volumes:
      - cartforge:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  backend:
    build: ./Backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ClickNcart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
    depends_on:
      - db

  frontend:
    build: ./Frondend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  cartforge: