apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: clickncart
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3       # AWS EBS — auto-provisioned
  resources:
    requests:
      storage: 2Gi